### PR TITLE
Random ingredient

### PR DESCRIPTION
**Pull request by ArmanAli05**
Logic for adding new users and random ingredients for the users. Tests will be needed to make sure this logic works

### CODE REVIEW

**Review by JoshuaRaybould — COMMENTED** [review]
Have you added the necessary type data (unit, liquid, solid) in the csv and altered the table so this can work?

**Comment by JoshuaRaybould** [comment]
Also I think we want to randomly create a date_time value (I guess you could get the current day's date in java an then take away a random number of days) then give the necessary information to the quality function so it can calculate quality, which you would then put in the database.

**Comment by JoshuaRaybould** [comment]
I am currently reorganising the code, in this I'll add the type column to the database, so I may then accept this request so we can all have access to the work you've done, but I do feel this section needs improvements, and certainty needs tests (as our code coverage has fell from around 70% to 45%).

**Comment by ArmanAli05** [comment]
Made the edits to the csv, but will need to upload a new one and delete the old one.

**Review by ArmanAli05 — COMMENTED** [review]
Made the relevant changes, need to add unit testing

**Comment by ArmanAli05** [comment]
> Have you added the necessary type data (unit, liquid, solid) in the csv and altered the table so this can work?

**Pull request closed without merging**
