### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ArmanAli05**

### CODE REVIEW

**Comment by JoshuaRaybould** [comment]
Most of it looks good, for eggs though would we want to just say eggs rather than specify 12 pack. There was a thing in the assignment brief that mentioned the camera could provided details such as quantities, so Id guess that if it saw a 12 pack it could maybe record it as 12 eggs. It's probably hard to come up with an exact price for a single egg, but anything reasonable should do.

**Comment by JoshuaRaybould** [comment]
Also it looks like some numbers seem to be written as strings here, do you know if that will work fine for getting them into the table in the database?

**Comment by varsityyy** [comment]
Had a look myself, I agree with you Josh i feel we should stick to singular items to make the implementation easier, and in terms of pricing it shouldn't be an issue as of now at least.

**Comment by ArmanAli05** [comment]
> Also it looks like some numbers seem to be written as strings here, do you know if that will work fine for getting them into the table in the database?

That's an excellent question, i think easiest thing to do would just be removing any commas and just having them as numbers as to not complicate things

**Pull request closed without merging**
